<?php

namespace App\Repositories;

use App\Presenters\ImportacoesPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\ImportacoesRepository;
use App\Entities\Importacoes;
use App\Validators\ImportacoesValidator;

/**
 * Class ImportacoesRepositoryEloquent
 * @package namespace App\Repositories;
 */
class ImportacoesRepositoryEloquent extends BaseRepository implements ImportacoesRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Importacoes::class;
    }

    /**
    * Specify Validator class name
    *
    * @return mixed
    */
    public function validator()
    {

        return ImportacoesValidator::class;
    }

    public function presenter()
    {
        return ImportacoesPresenter::class; // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}
